version: '2'

networks:
  vladimir-shared:
    external: true

volumes:
  caminio-websites-vol:

services:
  app:
    image: reg.tastenwerk.com:0.0.0
    restart: always
    command: puma -p4000
    env_file: defaults.env
    environment:
      RACK_ENV: production
    expose:
      - 7000
    networks:
      - vladimir-shared
